"use strict";




function filter(owner, rentablesList) {
	let out = [];
	
	const header = rentablesList.shift();
	
	/*	filtrer bort seksjoner med kontrakter 	*/
	out = out.filter((row) => {
			return (row[rentableIdx['løpenummer']] == '');
		});
	
	/*	filtrer etter eierform	*/
	out = rentablesList.filter((row) => {
			switch(owner) {
				case 'KF':
					return (row[rentableIdx['eierform']] == 'Tromsøbolig KF');
				
				case 'BK':
					let keep = false;
					keep |= (row[rentableIdx['eierform']] == 'Leid');
					keep |= (row[rentableIdx['eierform']] == 'Leid - Midlertidig bolig');
					keep |= (row[rentableIdx['eierform']] == 'Leid - Driftet');
					keep |= (row[rentableIdx['eierform']] == 'Tildelingsrett');
					return keep;
				
				default:
					return false;
			}
		});
	
	/*	filtrer etter aktiv / utleibar	*/
	out = out.filter((row) => {
			if (row[rentableIdx['aktiv']] == 'False') {
				return false;
			}
			if (row[rentableIdx['utleibar']] == 'False') {
				return false;
			}
			return true;
		});
	
	/*	filtrer etter utleiestatus	*/
	out = out.filter((row) => {
			return (row[rentableIdx['utleiestatus']] == 'Klar til tildeling');
		});
	
	
	rentablesList.unshift(header);
	out.unshift(header);
	
	return out;
}

function setupVacancyFilter() {
	const eventName = 'dataReady';
	let readyTarget = {
			fileA: 2
		};
	const readyEvent = new Event(eventName);
	let ready = new Proxy(readyTarget, {
			set: (target, key, value) => {
					target[key] = value;
					fxcd('download').disabled = true;
					if (target['fileA'] < 2) {
						fxcd('filter').disabled = false;
						if (target['fileA'] < 1) {
							document.dispatchEvent(readyEvent);
						}
					}
					return true;
				}
		});
	
	
	const spinner = fxcd('spinner');
	
	let inputData = null;
	
	fileChangeEvents(['rentables'], ready);
	
	
	document.addEventListener(eventName, () => {
			
			const btn = fxcd('download');
			btn.disabled = false;
			
			const owner = fxcd('owner').value;
			downloadButton(btn, filter(owner, inputData['rentables']), 'seksjoner klare for tildeling');
			
			hide(spinner);
		});
	
	fxcd('filter').onclick = () => {
			show(spinner);
			inputData = fileReadInput(['rentables'], ready);
		};
}


function vacancyTest() {
	
	const rentables = [
			['Nummer', 'Navn', 'Merknad', 'Adresse', 'Fasilitet', 'Eiendom', 'Bygning', 'Region', 'Kategori bolig', 'Formål', 'Status utleie', 'Plassering', 'Standard', 'Korreksjonsfaktorer', 'Seksjonstype', 'Mengde', 'Sum', 'Anskaffelsespris', 'Anskaffet dato', 'SSB nummer', 'Antall rom', 'Aktiv', 'Utleibar', 'Løpenummer', 'Leietaker nummer', 'Leietaker', 'Eierform'],
			['111610064', 'Alaskasvingen 4C', 'TV og internett inkludert i husleie. Standard hastighet. Canal Digital.  Dugnad i sameiet vår og snørydding av svalgang, trapp og foran heis på rullering Adkomst: 3 etg med trapp og heis Røyking og dyrehold: ikke tillatt Garasjeplass i parkeringsanlegg  Søppelsug midt på bygget - bruk brikke Se under fanen Dokument for mer informasjon', 'Alaskasvingen 4C  9013 TROMSØ ', '317201 Alaskasvingen 4', '3172 Alaskasvingen', '317201 Alaskasvingen 4', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Flyktningebolig', '77', '14754,6', '16 500', '01.04.2022', '', '3', 'False', 'False', '', '', '', 'Leid - Midlertidig bolig'],
			['111610065', 'Hagavegen 18, U0101', 'Fullt møblert, se dokumentfane. Internett, men ikke kabeltv., Kan bruke Chromecast Adkomst: ytterdør fra gateplan og deretter ned en trapp før inngangsdør. MERK: passer ikke for små barn Røyking og dyrehold: ikke tillatt Sokkelleilighet i enebolig. Privat utleier.  Se under fanen Dokument for mer informasjon', 'Hagavegen 18, U0101  9007 TROMSØ ', '317301 Hagavegen 18', '3173 Hagavegen 18', '317301 Hagavegen 18', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '75', '13783', '15 063', '01.04.2022', '', '3', 'True', 'False', '', '', '', 'Leid - Midlertidig bolig'],
			['112616383', 'Tomasjordnes 55, H0504', 'Leies ut inkludert strøm, varmtvann, internett og TV-signal. Kjøl- og fryseskap. Komfyr med separat koketopp. Oppvaskmaskin og vaskemaskin. Bod i bakkant av garasjeplass 55/504. Utleier: Øystein Barth-Heyerdahl 976 66 694. barthen72@gmail.com Eier erstatter hvitevarer som må skiftes pga normal slit og elde.    ', 'Tomasjordnes 55, H0504  9024 TOMASJORD ', '321001 Tomasjordnes 55', '3210 Tomasjordnes 55', '321001 Tomasjordnes 55', 'Fastlandet', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Flyktningebolig', '67', '13500', '15 000', '01.01.2023', '', '', 'False', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613171', 'Strandvegen 120, H0101', 'Delvis møblert Første etg, deler inngang med 2 andre boenheter. Parkering på anvist plass utenfor bygget. Ingen brøyting. Røyking og dyrehold tillatt. Mulighet for oppkobling til internett, må ordne selv. Bod i underetg. Mer info under fanen Dokument Kan benyttes til andre kategorier.', 'Strandvegen 120, H0101  9006 TROMSØ ', '123601 Strandvegen 120', '1236 Strandvegen 120', '123601 Strandvegen 120', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '75', '14216', '15 500', '01.04.2022', '', '4', 'True', 'True', '700', '', '', 'Leid - Midlertidig bolig'],
			['114613172', 'Hjalmar Johansens gate 184E', 'Delvis møblert UU standard, passer bevegelseshemmede, ingen trapper. Innlagt fiber  Andre detaljer, se fanen Dokument Bolig kan benyttes til andre leietakere Utleier: Atle Larsen Isfjordv 3 8480 Andenes Tlf 97186 770 atle_larsen@icloud.com', 'Hjalmar Johansens gate 184 - Bygg E  9007 TROMSØ ', '317401 Strandkanten Brygge E', '3174 Strandkanten Brygge E', '317401 Strandkanten Brygge E', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding fravikelse', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Tilpassede (UU+,og eller RK6) ', 'Komm.bolig', '44', '10999,2', '14 968', '04.04.2022', '', '2', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613173', 'Uranusvegen 37', 'Enebolig over 2 plan, med trappefri adkomst fra gateplan. 2 parkeringsplasser utenfor boligen. Møblert med hvitevarer. Ikke tillat med dyr/røyk. Mulighet med oppkobling til internett/tv, leietaker må bestille selv. Varmepumpe: Filter renset desember 2023. Må rensens hver 6. måned.  BOLIGKONTORETS KODE: 199091  BEBOERKODE: 234760 5 nøkler i sikringsskap til hybler inne i hus. ', 'Uranusvegen 37  9024 TOMASJORD ', '317501 Uranusvegen 37', '3175 Uranusvegen 37', '317501 Uranusvegen 37', 'Fastlandet', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding utgått', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '135', '20830', '26 000', '01.04.2022', '', '6', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613174', 'Idunnvegen 9, U0101', 'Delvis møblert, se fanen Dokument Bod i gang utenfor leil (ny dørlås kommmer) Internett inkludert. Ikke TV abonnement Blokk med felles inngang Europark forvalter p-plassene Ikke røyk inne, dyrehold ok Ikke HC-vennlig  Eier: Tony A. Berntsen 45473631 / tonybern@hotmail.com', 'Idunnvegen 9, U0101  9019 TROMSØ ', '317501 Idunnvegen 9', '3176 Idunnvegen 9', '317501 Idunnvegen 9', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til etter befaring', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', '', 'Komm.bolig', '70', '14087', '17 000', '01.04.2022', '', '4', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613177', 'Senjavegen 40', 'Leilighet i enebolig. Inkludert 1 parkeringsplass. Delvis møblert, røyk/dyr ikke tillatt, innvendig bod. Forbeholdt fremleie til ukrainske flyktninger', 'Senjavegen 40  9012 TROMSØ ', '317701 Senjavegen 40', '3177 Senjavegen 40', '317701 Senjavegen 40', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '75', '13483', '13 500', '11.04.2022', '', '3', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613178', 'Ishavsvegen 54, U0102, A', 'Eies av UNN. Kontaktperson Ragni Løkholm Ramberg epost: ragni.lokholm.ramberg@unn.no Tlf.: 97514546 Se dokumentfane', 'Ishavsvegen 54A, U0102  9010 TROMSØ ', '317801 Ishavsvegen 54', '3178 Ishavsvegen 54', '317801 Ishavsvegen 54', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Tildelt/under kontrakt', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', '', 'Komm.bolig', '80', '14021,4', '', '20.04.2022', '', '3', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613179', 'Ishavsvegen 54, U0101, B', 'Eies av UNN. Kontaktperson Ragni Løkholm Ramberg epost: ragni.lokholm.ramberg@unn.no Tlf.: 97514546 Se dokumentfane', 'Ishavsvegen 54B, U0101  9010 TROMSØ ', '317801 Ishavsvegen 54', '3178 Ishavsvegen 54', '317801 Ishavsvegen 54', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Under renovering', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', '', 'Komm.bolig', '80', '14021,4', '', '20.04.2022', '', '3', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['114613184', 'Grimsbyvegen 44, U0101', 'NB! Kjøleskap er beboer sitt (kjøpte nytt selv pga ødelagt), huseier erstatter ikke nytt.  Se arkfanen Dokument Fullt møblert. Inkluderer internett og parkering på sommeren. Da leiligheten er i en generasjonsbolig er det særdeles viktig å vise hensyn med tanke på støy, både i og utenfor leiligheten. Leier er ansvarlig for skade på balkong og trapp p.g.a. manglende snømåking. Røyk er ikke tillatt utenfor og inne i leiligheten. Dyrehold er ikke tillatt. Kan vurderes etter forespørsel.  Leiligheten er møblert, se inventarliste i overtakelsesprotokoll ', 'Grimsbyvegen 44, U0101  9011 TROMSØ ', '318001 Grimsbyvegen 44', '3180 Grimsbyvegen 44', '318001 Grimsbyvegen 44', '', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Komm.bolig', '85', '16010', '21 500', '02.05.2022', '', '4', 'False', 'False', '', '', '', 'Leid'],
			['114613185', 'Turistvegen 30, U0101', 'Kodelås - kode 020522 Se fanen Dokument. Delvis møblert. Leie inkluderer internett. Ikke parkering. Framleie er tillatt til ukrainske flyktninger Dyrehold ikke tillatt. Røyk ikke tillatt. Boligen er delvis møblert, se inventarliste i overtakelsesprotokoll. ', 'Turistvegen 30, U0101  9020 TROMSDALEN ', '318101 Turistvegen 30', '3181 Turistvegen 30', '318101 Turistvegen 30', 'Fastlandet', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '55', '12067', '12 500', '02.05.2022', '', '3', 'True', 'False', '', '', '', 'Leid'],
			['114613186', 'Utsikten 309', 'Eier: Troms og Finnmark fylkeskommune. NB! Bruksoverlating må søkes via fylkeskommunen, se fanen Dokument.  Husordensregler og snømåkekalender må videreformidles leietaker. Kabel-TV og internett inkludert. Parkering, garasjenr.145. Brikke til heis/garasje/trapperom. Røyking/dyrehold ikke tillatt. ', 'Utsikten 309  9018 TROMSØ ', '318201 Utsiken brl Fylkeskommunal', '3182 Utsiken brl Fylkeskommunal', '318201 Utsiken brl Fylkeskommunal', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '88', '15939,4', '17 559', '06.05.2022', '', '4', 'False', 'True', '', '', '', 'Leid'],
			['114613187', 'Einevegen 44', 'Strøm inkludert 1 stk parkeringsplass Leilighet i enebolig Inneholder Komfyr, Oppvaskmaskin Kjøl/frys  Kjellerleilighet uten eget bolignummer. Leies primært til flyktninger fra Ukraina.', 'Einevegen 44  9102 Kvaløysletta ', '318301 Einevegen 44', '3183 Einevegen 44', '318301 Einevegen 44', 'Kvaløya', 'Bolig', 'Ukrainabolig', '', 'Kvaløya, Hamna, Lunheim og Kroken', 'Normal', '', 'Komm.bolig', '53', '11192,4', '10 000', '12.05.2022', '', '2', 'True', 'True', '700', '', '', 'Leid'],
			['926010201', 'Seminarbakken 4, H0201, Rom 1', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0201  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding fravikelse', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,7', '12372', '13 747,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010202', 'Seminarbakken 4, H0202, Rom 2', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0202  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding utgått', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,5', '12204', '13 560,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010203', 'Seminarbakken 4, H0203, Rom 3', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0203  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til etter befaring', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,4', '12120', '13 466,7', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010204', 'Seminarbakken 4, H0204, Rom 4', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0204  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,5', '12204', '13 560,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010205', 'Seminarbakken 4, H0205, Rom 5', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0205  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Tildelt/under kontrakt', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,4', '12120', '13 466,7', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010206', 'Seminarbakken 4, H0206, Rom 6', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0206  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Under renovering', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,5', '12204', '13 560,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010207', 'Seminarbakken 4, H0207, Rom 7', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0207  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '11,8', '9932', '11 035,2', '01.12.2023', '', '1', 'False', 'False', '', '', '', 'Leid - Driftet'],
			['926010208', 'Seminarbakken 4, H0208, Rom 8', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0208  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '16,8', '14140', '15 711,2', '01.12.2023', '', '1', 'True', 'False', '', '', '', 'Leid - Driftet'],
			['926010209', 'Seminarbakken 4, H0209, Rom 9', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0209  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,5', '12204', '13 560,3', '01.12.2023', '', '1', 'False', 'True', '', '', '', 'Leid - Driftet'],
			['926010210', 'Seminarbakken 4, H0210, Rom 10', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0210  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,4', '12372', '13 747,3', '01.12.2023', '', '1', 'True', 'True', '700', '', '', 'Leid - Driftet'],
			['926010211', 'Seminarbakken 4, H0211, Rom 11', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0211  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding fravikelse', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '20,2', '17000', '18 890,9', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['926010212', 'Seminarbakken 4, H0212, Rom 12', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0212  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding utgått', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '15,6', '13130', '14 588,9', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['926010213', 'Seminarbakken 4, H0213, Rom 13', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0213  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til etter befaring', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '15,6', '13130', '14 588,9', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['926010214', 'Seminarbakken 4, H0214, Rom 14', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0214  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '15', '12625', '14 027,9', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['926010215', 'Seminarbakken 4, H0215, Rom 15', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0215  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Tildelt/under kontrakt', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,3', '12035', '13 373,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['926010216', 'Seminarbakken 4, H0216, Rom 16', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0216  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Under renovering', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,8', '12456', '13 840,8', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['114613217', 'Stakkevollvegen 303, H0211', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0211  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'False', 'False', '', '', '', 'Tildelingsrett'],
			['114613218', 'Stakkevollvegen 303, H0212', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0212  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'False', '', '', '', 'Tildelingsrett'],
			['114613219', 'Stakkevollvegen 303, H0213', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0213  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'False', 'True', '', '', '', 'Tildelingsrett'],
			['114613220', 'Stakkevollvegen 303, H0214', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0214  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '700', '', '', 'Tildelingsrett'],
			['114613221', 'Stakkevollvegen 303, H0215', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0215  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding fravikelse', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613222', 'Stakkevollvegen 303, H0216', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0216  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding utgått', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Tilpassede (UU+,og eller RK6) ', 'Flyktningebolig', '30', '10900', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613223', 'Stakkevollvegen 303, H0217', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0217  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til etter befaring', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Tilpassede (UU+,og eller RK6) ', 'Flyktningebolig', '30', '10900', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613224', 'Stakkevollvegen 303, H0218', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0218  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613225', 'Stakkevollvegen 303, H0219', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0219  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Tildelt/under kontrakt', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.09.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613226', 'Stakkevollvegen 303, H0220', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0220  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Under renovering', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett'],
			['114613207', 'Stakkevollvegen 303, H0201', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0201  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'False', 'False', '', '', '', 'Tromsøbolig KF'],
			['114613208', 'Stakkevollvegen 303, H0202', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0202  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'False', '', '', '', 'Tromsøbolig KF'],
			['114613209', 'Stakkevollvegen 303, H0203', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0203  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'False', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613210', 'Stakkevollvegen 303, H0204', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0204  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', '', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '700', '', '', 'Tromsøbolig KF'],
			['114613211', 'Stakkevollvegen 303, H0205', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0205  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding fravikelse', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,9', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613212', 'Stakkevollvegen 303, H0206', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0206  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Forhåndsmelding utgått', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613213', 'Stakkevollvegen 303, H0207', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0207  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til etter befaring', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613214', 'Stakkevollvegen 303, H0208', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0208  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613215', 'Stakkevollvegen 303, H0209', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0209  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Tildelt/under kontrakt', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF'],
			['114613216', 'Stakkevollvegen 303, H0210', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0210  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Under renovering', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF']
		];
	
	/*	expected result for KF	*/
	const wanted1 = [
			['Nummer', 'Navn', 'Merknad', 'Adresse', 'Fasilitet', 'Eiendom', 'Bygning', 'Region', 'Kategori bolig', 'Formål', 'Status utleie', 'Plassering', 'Standard', 'Korreksjonsfaktorer', 'Seksjonstype', 'Mengde', 'Sum', 'Anskaffelsespris', 'Anskaffet dato', 'SSB nummer', 'Antall rom', 'Aktiv', 'Utleibar', 'Løpenummer', 'Leietaker nummer', 'Leietaker', 'Eierform'],
			['114613214', 'Stakkevollvegen 303, H0208', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0208  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tromsøbolig KF']
		];
	
	/*	expected result for BK	*/
	const wanted2 = [
			['Nummer', 'Navn', 'Merknad', 'Adresse', 'Fasilitet', 'Eiendom', 'Bygning', 'Region', 'Kategori bolig', 'Formål', 'Status utleie', 'Plassering', 'Standard', 'Korreksjonsfaktorer', 'Seksjonstype', 'Mengde', 'Sum', 'Anskaffelsespris', 'Anskaffet dato', 'SSB nummer', 'Antall rom', 'Aktiv', 'Utleibar', 'Løpenummer', 'Leietaker nummer', 'Leietaker', 'Eierform'],			
			['114613177', 'Senjavegen 40', 'Leilighet i enebolig. Inkludert 1 parkeringsplass. Delvis møblert, røyk/dyr ikke tillatt, innvendig bod. Forbeholdt fremleie til ukrainske flyktninger', 'Senjavegen 40  9012 TROMSØ ', '317701 Senjavegen 40', '3177 Senjavegen 40', '317701 Senjavegen 40', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Normal', 'Ingen korreksjon', 'Komm.bolig', '75', '13483', '13 500', '11.04.2022', '', '3', 'True', 'True', '', '', '', 'Leid - Midlertidig bolig'],
			['926010204', 'Seminarbakken 4, H0204, Rom 4', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0204  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '14,5', '12204', '13 560,3', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid'],
			['926010214', 'Seminarbakken 4, H0214, Rom 14', 'Møblert (se inventarliste). Fellesarealer: Spiserom/kjøkken, oppholdsrom, vaskerom, 1 toalett, 6 bad. Parkering: 1 delt parkeringsplass foran inngang til 2. etg. Renhold: Fellesarealer blir vasket 2 ganger per uke.', 'Seminarbakken 4, H0214  9008 TROMSØ ', '092601 Seminarbakken 4', '0926 Seminarbakken 4', '092601 Seminarbakken 4', 'Tromsøya sør', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', '', 'Flyktningebolig', '15', '12625', '14 027,9', '01.12.2023', '', '1', 'True', 'True', '', '', '', 'Leid - Driftet'],
			['114613224', 'Stakkevollvegen 303, H0218', 'Studioleilighet på plan 2. Bygget har heis.  Fullt møblert med garderobe, dobbeltseng, vaskemaskin, håndklær, kjøl-og frys, koketopp og stekovn, vannkoker og kjøkkenutstyr.  WIFI inkludert. Ikke anledning til å henge opp noe eller ta hull i vegger. Ikke anledning til å supplere med ekstra møbler, kun ekstra seng. Røyking/dyrehold: ikke tillatt. Fellesarealer/atrium med gapahuk og benker. Ingen bod. Tilgang til sykkelparkering i felles låsbart rom. Ingen parkering. Postkasse merket med leilighetsnr ved inngang. Nøkkelbrikker. Søppel: ? Dagligvarebutikk i plan 1.', 'Stakkevollvegen 303 H0218  9019 TROMSØ ', '320201 Stakkevollvegen 303', '3202 Stakkevollvegen 303', '320201 Stakkevollvegen 303', 'Tromsøya nord', 'Bolig', 'Ukrainabolig', 'Klar til tildeling', 'Tromsøya (minus Hamna), Tromsdalen (Tomasjordnes - Solligården)', 'Høy', 'Ingen korreksjon', 'Flyktningebolig', '23,6', '9899,98', '', '01.10.2022', '', '1', 'True', 'True', '', '', '', 'Tildelingsrett']
		];
	
	
	let out = false;
	out |= compareCSV(wanted1, filter('KF', rentables));
	out |= compareCSV(wanted2, filter('BK', rentables));
	
	return out;
}


function unitTest() {
	return vacancyTest();
}